name: Lint

on: [push, pull_request]

jobs:
  client:
    runs-on: ubuntu-latest
    name: 'Client lint'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 17
      - run: npm ci
      - run: yarn run eslint ./packages/client

  server:
    runs-on: ubuntu-latest
    name: 'Server lint'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 17
      - run: npm ci
      - run: yarn run eslint ./packages/server
